# Generated by Django 3.0.3 on 2020-03-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageId',
            new_name='imagename',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pub_date',
        ),
    ]
